# Generated by Django 4.1 on 2023-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='remedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_remedio', models.CharField(max_length=45)),
                ('rem_preco', models.FloatField()),
                ('rem_quantidade', models.IntegerField()),
                ('rem_embalagem', models.CharField(choices=[['Envelope', 'Envelope'], ['Bisnaga', 'Bisnaga'], ['Bolsa', 'Bolsa'], ['Ampolas', 'Ampolas'], ['Seringa', 'Seringa'], ['Frasco', 'Frasco'], ['Blísteres', 'Blísteres']], max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Remédios',
            },
        ),
    ]
