# Generated by Django 4.1 on 2023-01-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedios',
            name='rem_embalagem',
            field=models.IntegerField(choices=[[1, 'Envelope'], [2, 'Bisnaga'], [3, 'Bolsa'], [4, 'Ampolas'], [5, 'Seringa'], [6, 'Frasco'], [7, 'Blísteres']]),
        ),
    ]
