# Generated by Django 4.1.5 on 2023-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_remedios_rem_embalagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedios',
            name='rem_embalagem',
            field=models.CharField(choices=[['Envelope', 'Envelope'], ['Bisnaga', 'Bisnaga'], ['Bolsa', 'Bolsa'], ['Ampolas', 'Ampolas'], ['Seringa', 'Seringa'], ['Frasco', 'Frasco'], ['Blísteres', 'Blísteres']], max_length=20),
        ),
    ]
